# Usa una imagen base con Python
FROM tiangolo/uvicorn-gunicorn

RUN mkdir /fastapi
COPY requirements.txt /fastapi

WORKDIR /fastapi


RUN pip install -r requirements.txt

COPY . /fastapi

EXPOSE 8000

# Ejecuta el script cuando el contenedor se inicia
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]

